apiVersion: v1
kind: Namespace
metadata:
  name: telegram-bots
---
apiVersion: v1
kind: Secret
metadata:
  name: slashbildbot-secrets
  namespace: telegram-bots
type: Opaque
data:
  BOT_TOKEN: "{{BOT_TOKEN}}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slashbildbot
  namespace: telegram-bots
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slashbildbot
  template:
    metadata:
      labels:
        app: slashbildbot
    spec:
      containers:
        - name: slashbildbot
          image: torbencarstens/slashbildbot:{{DOCKER_TAG}}
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: slashbildbot-secrets
