apiVersion: v1
kind: Namespace
metadata:
  name: telegram-bots
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slashbildbot-state-pvc
  namespace: telegram-bots
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
---
apiVersion: v1
kind: Secret
metadata:
  name: slashbildbot-secrets
  namespace: telegram-bots
type: Opaque
data:
  BOT_TOKEN: "{{BOT_TOKEN}}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slashbildbot
  namespace: telegram-bots
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slashbildbot
  template:
    metadata:
      labels:
        app: slashbildbot
        dockertag: {{DOCKER_TAG}}
    spec:
      containers:
        - name: slashbildbot
          image: torbencarstens/slashbildbot:{{DOCKER_TAG}}
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: slashbildbot-secrets
          volumeMounts:
            - mountPath: "/data"
              name: slashbildbot-state-volume
      volumes:
        - name: slashbildbot-state-volume
          persistentVolumeClaim:
            claimName: slashbildbot-state-pvc

